name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        run: rustup default nightly && rustup component add clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --workspace --verbose --lib
      - name: Run linter
        run: cargo clippy --all -- -D warnings
